apiVersion: apps/v1
kind: Deployment
metadata: 
  name: eigworker
  labels: 
    app: cpuint
    tier: cloud
    role: worker
spec: 
  # replicas: 2
  selector: 
    matchLabels: 
      app: cpuint
      tier: cloud
      role: worker
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: cpuint
        tier: cloud
        role: worker
    spec: 
      containers: 
      - image: liju666/cpuint_eigen:latest
        name: sortworker
        env: 
        - name: REDIS_HOST
          value: cloudredis
        resources: 
          requests: 
            memory: "1Gi"
            cpu: "1000m"
          limits: 
            memory: "2Gi"
            cpu: "2000m"
      nodeSelector: 
        centre: "true"
