apiVersion: v1
kind: Service
metadata: 
  name: cloudredis
  labels: 
    app: cpuint
    tier: cloud
spec: 
  ports: 
    - name: redis
      port: 6379
      targetPort: 6379
    # - name: flower
    #   port: 8888
    #   targetPort: 8888
  selector: 
    app: cpuint
    tier: cloud
    role: broker
