kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1
metadata: 
  name: edgehpa1
spec: 
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: sortworker1
  targetCPUUtilizationPercentage: 60
