apiVersion: v1
kind: Service
metadata: 
  name: entrypoint1
spec:
  selector: 
    app: cpuint
    tier: edge
    role: worker
    zone: "1"
  ports: 
    - port: 5000
      targetPort: 5000
  type: NodePort
