# kind: HorizontalPodAutoscaler
# apiVersion: autoscaling/v2beta1
# metadata: 
#   name: edgehpa0
# spec: 
#   maxReplicas: 5
#   minReplicas: 2
#   scaleTargetRef: 
#     apiVersion: apps/v1
#     kind: Deployment
#     name: sortworker0
#   metrics: 
#   - type: Pods
#     pods: 
#       metricName: cpu_usage
#       targetAverageValue: "500m"
